apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
  labels:
    app.kubernetes.io/name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: strapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: strapi
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-18T18:30:00Z"
    spec:
      containers:
      - name: strapi
        image: your-registry/strapi:5-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
          name: http
        env:
        - name: DATABASE_CLIENT
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: DATABASE_CLIENT
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-postgresql
              key: password  # Changed from postgresql-password
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: PORT
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: PUBLIC_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: NODE_ENV
        - name: APP_KEYS
          valueFrom:
            secretKeyRef:
              name: strapi-secrets
              key: APP_KEYS
        - name: API_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: strapi-secrets
              key: API_TOKEN_SALT
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-secrets
              key: ADMIN_JWT_SECRET
        - name: TRANSFER_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: strapi-secrets
              key: TRANSFER_TOKEN_SALT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-secrets
              key: JWT_SECRET
        - name: STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE
        - name: STRAPI_TELEMETRY_DISABLED
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: STRAPI_TELEMETRY_DISABLED
        - name: STRAPI_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: STRAPI_LOG_LEVEL
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: DANGEROUSLY_DISABLE_HOST_CHECK
        - name: VITE_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: VITE_ALLOWED_HOSTS
        - name: STRAPI_ADMIN_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: STRAPI_ADMIN_BACKEND_URL
        - name: ADMIN_PATH
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: ADMIN_PATH
        - name: VITE_HMR_HOST
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: VITE_HMR_HOST
        - name: VITE_HMR_PORT
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: VITE_HMR_PORT
        - name: STRAPI_DISABLE_UPDATE_NOTIFICATION
          value: "true"
        - name: STRAPI_HIDE_STARTUP_MESSAGE
          value: "true"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=4096"
        command: ["yarn", "start"]
        args: []
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
        volumeMounts:
        - name: strapi-data
          mountPath: /opt/app/data
        - name: strapi-uploads
          mountPath: /opt/app/public/uploads
        - name: strapi-data
          mountPath: /opt/app/src/api
          subPath: src-api
        - name: strapi-data
          mountPath: /opt/app/.strapi
          subPath: strapi-metadata
        - name: strapi-data
          mountPath: /opt/app/src
          subPath: src
        - name: vite-config
          mountPath: /opt/app/vite.config.admin.js
          subPath: vite.config.admin.js
        livenessProbe:
          httpGet:
            path: /_health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: strapi-data
        persistentVolumeClaim:
          claimName: strapi-data
      - name: strapi-uploads
        persistentVolumeClaim:
          claimName: strapi-uploads
      - name: vite-config
        configMap:
          name: strapi-vite-config
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: strapi
              topologyKey: kubernetes.io/hostname
