apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-data
  namespace: strapi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 8Gi
